### ISSUE TITLE
Integration in PEASS-ng

### ISSUE THREAD

**Issue by carlospolop** [61106960/adPEAS#1]
Hi mate!
This tool looks interesting
Because of the name and that I was thinking about creating a Winpeas in powershell, let me know if you would be interested in maintaining it the PEASS-ng repository with the rest of the PEASSes (keeping your authority over your tool obviously)

**Comment by 61106960** [comment]
I really appreciate that you want to include adPEAS in PEASS-ng. Feel free to fork it to your repo and I will try to find time to contribute. I guess the process of fixing bugs and implementing new things will speed up with the help of more contributors.
Just keep in mind, that I won't have the time to take care of all the issues and pull requests, which indeed will popup if adPEAS is hosted in your amazing PEASS-ng suite. By the way, I really love linPEAS and winPEAS and your idea inspired me to code something similar for Active Directory.

**Comment by carlospolop** [comment]
Cool, however, in order for this script to be a new PEASS I need to ask you for some "small" changes/additions that I hope you agree with:
- Add a PEASS ascii or ansi art (you can copy Winpeas from the .exe so it has colors if you don't want to create a new one)
- Use the same characters as Winpeas too identify section titles and links with references so https://github.com/carlospolop/PEASS-ng/blob/master/parser/peass-parser.py can create a JSON of the report (soon I will release a way to transform that JSON to HTML)
- Use at least the red color to color output that is suspicious and/or could lead to privesc somehow. This one is pretty important as that's the signature of the PEAS Suite.

**Comment by 61106960** [comment]
I will implement it as soon I have time and will come back to you. It's likely that it will take some time.....

**Comment by 61106960** [comment]
It took some time but now I've added ANSI color and did some re-work of code. So, if you still like you can give it a try.

**Comment by AkechiShiro** [comment]
@61106960 any news on this integration ?

**Comment by 61106960** [comment]
I guess it is up to @carlospolop, if he likes to implement/bundle it.

**Comment by carlospolop** [comment]
Hi @61106960,
Have you though how would you like to do this?
Would you prefer to move the script to the PEASS-ng repo and add you there as collaborator so you can modify the script.  Or would you prefer to maintain it here and set a GH action to send a PR to the PEASS repo everytime you update it?

Also, would you mind adding the winpeass banner to the output of adpeas?

**Comment by 61106960** [comment]
I will think about a good strategy to have it included in your PEASS-ng suite.

**Comment by TalhaKircili** [comment]
@61106960 any news on this integration ?

**Comment by 61106960** [comment]
I've thought about it and I'd like to leave it as it is. So no integration in PEASS-ng but I appreciate the request to integrate it.

**Comment by AkechiShiro** [comment]
Thanks @61106960, if someone else wants to work on integrating it, could they ?

**Comment by 61106960** [comment]
Indeed, it's a free world ;-)
