### ISSUE TITLE
Making adPEAS "prettier"

### ISSUE THREAD

**Issue by 0xXyc** [61106960/adPEAS#3]
Is there any way we can add some color or improve the formatting of this tool? This work is amazing and I feel like this tool could seriously be 100x better (than it already is) with some TLC. Thank you!

**Comment by Khatcode** [comment]
It already looks good imo. It doesn't have too much fluff and gets to the point with what it does.

**Comment by 61106960** [comment]
I am working on some re-factoring of code and one part of this task is output formatting.......

**Comment by JakeSwiz** [comment]
> It already looks good imo. It doesn't have too much fluff and gets to the point with what it does.

Simply constructive criticism :) I think it's an excellent tool and it looks great too.

**Comment by 61106960** [comment]
From adPAS version 0.8.0 there are now used colors for screen and file output. If needed, color can be suppresed with the switch -nocolor.
