### ISSUE TITLE
Bloodhound -CollectionMethod issue

### ISSUE THREAD

**Issue by init5-SF** [61106960/adPEAS#4]
hello,

the official bloodhound powershell collector supports using `-CollectionMethod "all,gpolocalgroup" `
When I tried this with adPEAS it failed, any way to fix this?

![image](https://user-images.githubusercontent.com/10214861/217269503-95d99239-ff84-4b88-809b-3058089ab5be.png)

Thanks for the great script btw!

**Comment by 61106960** [comment]
I am working on an updated version of adPEAS at the moment and there will be the current PS version of the SharpHound collector included, which will fix your described issue.

**Comment by 61106960** [comment]
Should be fixed in the adPEAS version 0.8.0
