### ISSUE TITLE
AS-REPRoasting not working as expected

### ISSUE THREAD

**Issue by init5-SF** [61106960/adPEAS#5]
Hello, thanks for the great tool!

I'm testing the script and its working perfect, but the as-reproasting is throwing a weird error for some reason.
Screenshot:
![image](https://github.com/61106960/adPEAS/assets/10214861/dabbb83b-452e-4238-8eb2-f2f0059d3fa6)

Both identified accounts do have the Kerberos PreAuth not required
![image](https://github.com/61106960/adPEAS/assets/10214861/4ee10ca2-d8f8-458b-971c-24ca025181af)

Test env:
```
PowerShell version:  5.1
Domain Controller: Windows Server 2022 (21H2)
```

**Comment by 61106960** [comment]
This happens if the user account is expired. I do not check upfront for expired accounts, but just for disabled ones. Therefore adPEAS tries to do the ASREP, but fails because the account is locked due to the set expire date.

**Comment by init5-SF** [comment]
Ok, got it! Thank you!
