### ISSUE TITLE
In ConvertFrom-SID function, the built-in SIDs do not correspond with the Microsoft documentation

### ISSUE THREAD

**Issue by levk-cye** [61106960/adPEAS#8]
For example, see "S-1-5-17". In Microsoft documentation, it is "IUSR" account, but in this function, it is "This organization " group (including the space in the end of the name).

**Comment by 61106960** [comment]
Thanks for the hint.

I fixed all SID's according to https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/manage/understand-security-identifiers
